<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <header>
      <h1>Le Blog de la 3WA</h1>
      <nav>
        <a href="#">Accueil</a>
        <a href="#">A propos</a>
        <a href="#"></a>
      </nav>
      <form class="" action="search.php" method="post">
        <input type="text" name="mot" value="" placeholder="Entrez un mot" />
        <input type="submit" name="chercher" value="Rechercher">
      </form>
    </header>
    <main>
      <?php include $template ?>
    </main>
    <footer>

    </footer>
  </body>
</html>
